<a href="https://colab.research.google.com/github/A050E107/AI-WORK/blob/master/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
print("pandas version: %s" % pd.__version__)

pandas version: 0.24.2


In [4]:
import numpy as np
x = np.array([[1,2.3],[0,0],(1+1j,3.)])
print(x)

[[1. +0.j 2.3+0.j]
 [0. +0.j 0. +0.j]
 [1. +1.j 3. +0.j]]


In [6]:
import numpy as np 

#z=np.linspace(2.0, 3.0, num=5, endpoint=False)

print(z)

[1.  1.6 2.2 2.8 3.4 4. ]


In [11]:
import numpy as np

z=np. linspace(1., 4, 6) #start. end. num

print(z)

[1.  1.6 2.2 2.8 3.4 4. ]


In [16]:
import numpy as np

np.linspace(2.0, 3.0, num=5, endpoint=False)



array([2. , 2.2, 2.4, 2.6, 2.8])

In [15]:
import numpy as np

np.linspace(2.0, 3.0, num=5, retstep=True)


(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [14]:
import numpy as np

np.linspace(2.0, 3.0, num=5, retstep=True)


(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)